demo_site/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from projects.models import Project
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
url(r'^admin/', include(admin.site.urls)),
url(r'^projects/$', 'projects.views.index'),
url(r'^$', 'projects.views.index'),
url(r'^projects/(?P<project_id>\d+)/$', 'projects.views.detail', name="detail"),
url(r'^projects/add$', 'projects.views.project_add', name="add"),
url(r'^projects/(?P<project_id>\d+)/ticket/add$', 'projects.views.ticket_add', name="ticket_add"),
url(r'^projects/(?P<project_id>\d+)/edit$', 'projects.views.edit', name="edit"),
url(r'^projects/(?P<project_id>\d+)/ticket/(?P<ticket_id>\d+)/edit$', 'projects.views.ticket_edit', name="ticket_edit"),
url(r'^projects/(?P<project_id>\d+)/delete$', 'projects.views.delete', name="delete"),
url(r'^projects/(?P<project_id>\d+)/ticket/(?P<ticket_id>\d+)/delete$', 'projects.views.ticket_delete', name="ticket_delete"),
url(r'^login/$', 'projects.views.login_user'),
url(r'^logout/$', 'projects.views.logout'),
url(r'^projects/(?P<project_id>\d+)/ticket/(?P<ticket_id>\d+)$', 'projects.views.ticket_detail', name="ticket_detail"),
url(r'^projects/search/$','projects.views.search', name="search"),
url(r'^search/$','projects.views.search', name="search"),

)

projects/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.forms.fields import DateField

class Project(models.Model):
  project_user = models.ManyToManyField(User, related_name = 'project_user')
  user = models.ForeignKey(User)
  name = models.CharField(max_length = 40)
  description = models.CharField(max_length = 100)
  start_date = models.DateTimeField('Start date')
  end_date = models.DateTimeField('End date')
  def __unicode__(self):
    return self.name
  def owner_by_user(self, user):
    return self.user == user

  class Meta:
    permissions = (
      ("can_add_projects", "Can add projects"),
      )

class Status(models.Model):
  status_name = models.CharField(max_length = 40)
  def __unicode__(self):
    return self.status_name

class Ticket(models.Model):
  user = models.ForeignKey(User)
  project = models.ForeignKey(Project)
  status = models.ForeignKey(Status)
  name = models.CharField(max_length = 40)
  description = models.CharField(max_length = 100)
  def __unicode__(self):
    return self.user
  def owner_by_user(self, user):
    return self.user == user

  class Meta:
    permissions = (
      ("can_add_tickets", "Can add tickets"),
      )

class TicketForm(ModelForm):
  class Meta:
    model = Ticket
    exclude = ('user', 'project')



class ProjectForm(ModelForm):
  class Meta:
    model = Project
    exclude = ('user')

projects/views.py
# Create your views here.
from django.conf.urls.defaults import patterns, include, url
from projects.models import Project, Ticket, User, Status, TicketForm, ProjectForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render_to_response, render, redirect, get_list_or_404
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.template import loader, Context

def index(request):
  if request.user.is_authenticated():
    latest_project_list = Project.objects.all().order_by('start_date')[:15]
    return render_to_response('projects/index.html', {'latest_project_list':
    latest_project_list}, context_instance=RequestContext(request))
  else:
    return redirect(login_user)

def search(request):
  query = request.GET.get('q', '')
  if query != "":
    projects = Project.objects.filter(name__contains=query)
    return render(request, 'projects/results.html', {"projects" : projects})
    projects = []



def logout(request):
  auth_logout(request)
  request.flash['notice'] = 'Logged out!'
  return redirect(login_user)

def project_for_user(request):
  user = request.user
  projects = Projects.objects.filter(added_by_user = user)

def detail(request, project_id):
  if request.user.is_authenticated():
    project = get_object_or_404(Project, pk= project_id)
    users = project.project_user.all()
    return render_to_response('projects/detail.html', {'project' : project, 'users' : users },
    context_instance=RequestContext(request))
  else:
    return redirect(login_user)

def ticket_detail(request, ticket_id, project_id):
  if request.user.is_authenticated():
    project = get_object_or_404(Project, pk= project_id)
    ticket = get_object_or_404(Ticket, pk= ticket_id)
    return render_to_response('projects/ticket_detail.html', {'ticket' : ticket, 'project' : project},
    context_instance=RequestContext(request))
  else:
    return redirect(login_user)

def login_user(request):
  state = "Log in"
  username = password = ''
  if request.method == "POST":
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)
    if user is not None:
      if user.is_active:
        login(request, user)
        request.flash['notice'] = 'Logged in'
        return redirect(index)
    else:
      request.flash['warning'] = 'Wrong details'
  if request.user.is_authenticated():
    return redirect(index)

  return render_to_response('projects/auth.html',{'state':state, 'username': username},
  context_instance=RequestContext(request))

def project_add(request):
  if request.user.is_authenticated():
    if request.method == "POST":
      form = ProjectForm(request.POST)
      if form.is_valid():
        form.instance.user = request.user
        form.save()
        request.flash['notice'] = 'Project added'
        return redirect(index)
    else:
      form = ProjectForm()
  else:
    return redirect(login_user)

  return render(request, 'projects/add.html', {'form' : form})

def ticket_add(request, project_id):
  if request.user.is_authenticated():
    project = get_object_or_404(Project, pk= project_id)
    users = project.project_user.all()
    user = request.user
    if user in users or project.owner_by_user(user):
      if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
          form.instance.user = request.user
          project = get_object_or_404(Project, pk = project_id)
          form.instance.project = project
          form.save()
          request.flash['notice'] = 'Ticket added'
          return redirect('detail', project.id)
      else:
        form = TicketForm()
    else:
      request.flash['warning'] = 'You are not the owner of the project or an assigned user to the project!'
      return redirect('detail', ticket.id)
  else:
    return redirect(login_user)

  return render(request, 'projects/ticket_add.html', {'form' : form})


def delete(request, project_id):
  project = get_object_or_404(Project, pk = project_id)
  if project.owner_by_user(request.user):
    if request.method == "GET":
      project.delete()
      request.flash['notice'] = 'Project deleted'
      return redirect(index)
  else:
    request.flash['warning'] = 'You are not the owner of this project'
    return redirect('detail', project.id)

def ticket_delete(request, ticket_id, project_id):
  ticket = get_object_or_404(Ticket, pk = ticket_id)
  project = get_object_or_404(Project, pk = project_id)
  if ticket.owner_by_user(request.user):
    if request.method == "GET":
      project = get_object_or_404(Project, pk = project_id)
      ticket.delete()
      request.flash['notice'] = 'Ticket deleted'
      return redirect('detail', project.id)
  else:
    request.flash['warning'] = 'You are not the owner of this ticket'
    return redirect('ticket_detail', project.id, ticket.id)

def edit(request, project_id):
  if request.user.is_authenticated():
    project = get_object_or_404(Project, pk = project_id)
    if project.owner_by_user(request.user):
      if request.method == "POST":
        form = ProjectForm(request.POST, instance = project)
        if form.is_valid():
            form.save()
            request.flash['notice'] = 'Project edited'
            return redirect('detail', project.id)
      else:
        form = ProjectForm(instance = project)
      return render(request,  'projects/edit.html' , {"form" : form, "project" : project })
    else:
      request.flash['warning'] = 'You are not the owner of this project'
      return redirect('detail', project.id)
  else:
    return redirect(login_user)

def ticket_edit(request, ticket_id, project_id):
  if request.user.is_authenticated():
    ticket = get_object_or_404(Ticket, pk = ticket_id)
    project = get_object_or_404(Project, pk = project_id)
    if ticket.owner_by_user(request.user):
      if request.method == "POST":
        form = TicketForm(request.POST, instance = ticket)
        if form.is_valid():
          form.save()
          request.flash['notice'] = 'Ticket edited!'
          return redirect('ticket_detail', project.id, ticket.id)
      else:
        request.flash['notice'] = 'Ticket fel!'
        form = TicketForm(instance = ticket)
      return render(request,  'projects/ticket_edit.html' , {"form" : form, "ticket" : ticket })
    else:
      request.flash['warning'] = 'You are not the owner of this ticket'
      return redirect('ticket_detail', project.id, ticket.id)
  else:
    return redirect(login_user)

projects/templates/projects/add.html
<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
<div class="span11">
        <div id="project">
{% block title %}

<h1>Add project</h1>

{% endblock %}



{% block content %}

<form action="{{ project_add}}" method="POST"> {% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Add project" />
</form>

{% endblock %}
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />
<a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/auth.html
 <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

<div class="span11">
        <div id="project">
<h2>CU Project Manager</h2>
 <br />
 {% for message in flash.notice %}
    <div id="flash">{{ message }}</div>
{% endfor %}
{% for message in flash.warning %}
    <div id="warning">{{ message }}</div>
{% endfor %}

  <form action="{{ login_user }}" method="POST">
    {% csrf_token %}

    {% if next %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% endif %}
    username:
    <input type="text" name="username" value="{{ username}}" /><br />
    password:
    <input type="password" name="password" value="" /><br />

    <input type="submit" value="Log In" />
  </form>
</div>
</div>

projects/templates/projects/detail.html
{% load custom_filters %}
<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <div class="span11">
        <div id="project">

 <br />
 {% for message in flash.notice %}
    <div id="flash">{{ message }}</div>
{% endfor %}
{% for message in flash.warning %}
    <div id="warning">{{ message }}</div>
{% endfor %}

<br />

<h1>{{ project.name }}</h1>

Description: {{ project.description}}
<br />

Start date: {{ project.start_date}}
<br />
End date: {{ project.end_date}}
<br />
Owner:  {{ project.user.username}}
<br />
<br />

Project users:
<br />
{% for users in users %}
{{ users.username }}

<br />
  {% endfor %}
<br />

<div class="ticketlist">
Tickets:
{% for ticket in project.ticket_set.all %}

        <li><a href="{% url ticket_detail project.id ticket.id%}">{{ ticket.name }}</a>   Owner: {{ ticket.user.username }}</li>
    {% endfor %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</div>
<br />
{% if user in users or project|ownership:user %}
<a href="{% url ticket_add project.id %}"><h3>Add a ticket for {{ project.name }}</h3></a>
<br />
{% endif %}

<br />
{% if project|ownership:user %}
<a href="{% url edit project.id %}"><h3>Edit this project</h3></a>

<a href="{% url delete project.id %}"><h3>Delete this project</h3></a>
{% endif %}
<a href="/projects/">Back to list</a>
<br />
<a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/edit.html
<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <div class="span11">
        <div id="project">

<form action="{{ edit }}" method = 'post' >
  {% csrf_token %}
{{ form.as_p }}


    <input type="submit" value="Edit project">
  </form>
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />
  <a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/index.html
{% load staticfiles %}


<!-- Le styles -->
     <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
     <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

      <div class="span11">
        <div id="project">
          <h2>CU Project Manager</h2>
 <form method="get" action="search">
{{ request.user.id }}
  <p>Search:
  <input type="text" name="q" id="query" />
  <input type="submit" value="Submit" /></p>
 </form>


 <br />
 {% for message in flash.notice %}
    <div id="flash">{{ message }}</div>
{% endfor %}
{% for message in flash.warning %}
    <div id="warning">{{ message }}</div>
{% endfor %}
{% if latest_project_list %}

<div class="ticketlist"
<h3> Projects </h3>

    {% for proj in latest_project_list %}


        <li><a href="{% url detail proj.id %}">{{ proj.name }}</a></li>

    {% endfor %}

      </div>
{% else %}
    <p>No projects are available.</p>
{% endif %}


<a href="{% url add %}"><h3>Add a project</a></h3>

<br />

<a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/results.html
 <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <div class="span11">
        <div id="project">

<h3>Search results: ({{ projects.count }})</h3>
  {% for p in projects %}
<ul>
<div class="ticketlist">
Name: <a href="/projects/{{ p.id }}/">{{ p.name }}</a>
<br />
Owner: {{ p.user }}
</div>

 </ul>
{% endfor%}
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />
<a href="/logout/">logout</a>

</div>
</div>

projects/templates/projects/ticket_add.html
<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

     <div class="span11">
        <div id="project">
{% block title %}

<h1>Add ticket</h1>

{% endblock %}





{% block content %}

<form action="{{ticket_add}}" method="POST"> {% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Add Ticket" />
</form>

{% endblock %}


<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />

<a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/ticket_detail.html
{% load custom_filters %}

<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <div class="span11">
        <div id="project">
          {% for message in flash.notice %}
    <div id="flash">{{ message }}</div>
{% endfor %}
{% for message in flash.warning %}
    <div id="warning">{{ message }}</div>
{% endfor %}

<br />

<h1>Name: {{ ticket.name }}</h1>

Status: {{ ticket.status.status_name}}
<br />
Description: {{ ticket.description}}
<br />
Owner:  {{ ticket.user.username}}
<br />

{% if ticket|ownership:user %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<br />
<a href="{% url ticket_edit project.id ticket.id %}"><h3>Edit this ticket</h3></a>

<a href="{% url ticket_delete project.id ticket.id %}"><h3>Delete this ticket</h3></a>
{% endif %}
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />
<a href="/logout/">logout</a>
</div>
</div>

projects/templates/projects/ticket_edit.html
<!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
       <title>CU Project Manager</title>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <div class="span11">
        <div id="project">

<form action="{{ ticket_edit }}" method = 'post' >
  {% csrf_token %}
{{ form.as_p }}


    <input type="submit" value="Edit ticket">
  </form>
<input type=button value="Previous Page" onClick="javascript:history.go(-1);">
<br />
  <a href="/logout/">logout</a>
</div>
</div>